{% set name = "konlpy" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1b576aef07d094706e4bae446ab835855abbe806647fe861243c378482eb79c6

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jpype1 >=0.7.0
    - lxml >=4.1.0
    - numpy >=1.6

test:
  imports:
    - konlpy
  requires:
    - pip
    - pytest
    - openjdk
  source_files:
    - test
  commands:
    - pip check
    {% set ignore_tests = " --ignore=test/test_mecab.py" %}  # requires mecab
    - pytest {{ ignore_tests }}

about:
  home: http://konlpy.org
  dev_url: https://github.com/konlpy/konlpy
  doc_url: https://konlpy.org
  summary: KoNLPy is a Python package for natural language processing of the Korean language.
  description: |
    KoNLPy is a Python library for Korean natural language processing (NLP), providing tools for tokenization,
    part-of-speech tagging, and morphological analysis using various Korean NLP engines like Mecab, Hannanum, and Komoran.
    It is widely used for text preprocessing in applications such as sentiment analysis, machine translation, and information retrieval.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Jrice1317
