{% set name = "konlpy" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1b576aef07d094706e4bae446ab835855abbe806647fe861243c378482eb79c6

build:
  skip: True                                    # [py<38 or py>=312]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jpype1 >=0.7.0
    - lxml >=4.1.0
    - numpy >=1.6

test:
  imports:
    - konlpy
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - test

about:
  home: http://konlpy.org
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mohamedlarbisentissi
